ecommerce/authcart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.handlelogin,name='handlelogin'),
    path('logout/',views.handlelogout,name='handlelogout'),
    # path('activate/<uidb64>/<token>',views.ActivateAccountView.as_view(),name='activate'),
    path('request-reset-email/',views.RequestResetEmailView.as_view(),name='request-reset-email'),
    path('set-new-password/<uidb64>/<token>',views.SetNewPasswordView.as_view(),name='set-new-password'),
    path('activate/<uidb64>/<token>/', views.ActivateAccountView.as_view(), name='activate'),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("ecommerceapp.urls")),
    path('auth/',include("authcart.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/ecommerceapp/models.py
from django.db import models

# Create your models here.
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    desc = models.TextField(max_length=500)
    phonenumber = models.IntegerField()
    image = models.ImageField(upload_to='images')  # Updated upload_to path

    def __str__(self):  # Corrected the method name
        return self.name



class Product(models.Model):
    product_id = models.AutoField
    product_name = models.CharField(max_length=100)
    category = models.CharField(max_length=100, default="")
    subcategory = models.CharField(max_length=50, default="")
    price = models.IntegerField(default=0)
    desc = models.CharField(max_length=300)
    image = models.ImageField(upload_to='images/images')

    def __str__(self):
        return self.product_name






class Orders(models.Model):
    order_id = models.AutoField(primary_key=True)
    items_json =  models.CharField(max_length=5000)
    amount = models.IntegerField(default=0)
    name = models.CharField(max_length=90)
    email = models.CharField(max_length=90)
    address1 = models.CharField(max_length=200)
    address2 = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=100)    
    oid=models.CharField(max_length=150,blank=True)
    amountpaid=models.CharField(max_length=500,blank=True,null=True)
    paymentstatus=models.CharField(max_length=20,blank=True)
    phone = models.CharField(max_length=100,default="")
    def __str__(self):
        return self.name


class OrderUpdate(models.Model):
    update_id = models.AutoField(primary_key=True)
    order_id = models.CharField(max_length=150)  # Change this field to CharField
    update_desc = models.CharField(max_length=5000)
    delivered = models.BooleanField(default=False)
    timestamp = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.update_desc[0:7] + "..."

ecommerce/templates/activatefail.html
<h1>Something went wrong</h1>

ecommerce/templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Check Out {% endblock title %}

{% block content %}
<section id="hero" style="width: 100%; height: 90vh; background-image: url('{% static 'images/money.jpg' %}'); background-position: top center; background-size: cover; position: relative;">
  <div class="hero-container">
    <h1>Checkout</h1>
  </div>
</section>
{% endblock content %}

{% block body %}
{% load static %}

<section id="portfolio" class="portfolio">
  <div class="container">
    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
      <strong>{{message}}</strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}

    {% comment %} <div class="section-title">
      <h3>Checkout Page</h3>
    </div> {% endcomment %}

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="card">
            <div class="card-body">
              <h2 class="card-title text-center">Your Cart</h2>
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">Item</th>
                      <th scope="col">Quantity</th>
                      <th scope="col">Price</th>
                      <th scope="col">Total Price</th>
                    </tr>
                  </thead>
                  <tbody id="cartTableBody">
                    <!-- Cart items will be dynamically inserted here -->
                  </tbody>
                  <tr>
                    <td colspan="2"></td>
                    <td class="text-right"><b>Total:</b></td>
                    <td><b><span id="totalprice"></span></b></td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container" style="margin-top:20px">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="card mb-4">
            <div class="card-body">
              <h2 class="card-title text-center">Enter Address & Other Details to Buy:</h2>
              <form id="checkoutForm" method="post" action="/checkout/" class="needs-validation" novalidate>
                {% csrf_token %}
                <input type="hidden" name="itemsJson" id="itemsJson" />
                <input type="hidden" id="amt" name="amt" />
                <div class="mb-3">
                  <label for="inputname" class="form-label">Name</label>
                  <input type="text" class="form-control" id="name" name="name" placeholder="Name" required />
                  <div class="invalid-feedback">
                    Please enter your name.
                  </div>
                </div>
                <div class="mb-3">
                  <label for="inputEmail4" class="form-label">Email</label>
                  <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="{{user.email}}" required />
                  <div class="invalid-feedback">
                    Please enter a valid email address.
                  </div>
                </div>
                <div class="mb-3">
                  <label for="inputAddress" class="form-label">Address</label>
                  <input type="text" class="form-control" id="address1" name="address1" placeholder="1234 Main St" required />
                  <div class="invalid-feedback">
                    Please enter your address.
                  </div>
                </div>
                <div class="mb-3">
                  <label for="inputAddress2" class="form-label">Address line 2</label>
                  <input type="text" class="form-control" id="address2" name="address2" placeholder="Apartment, studio, or floor" required />
                  <div class="invalid-feedback">
                    Please enter your address line 2.
                  </div>
                </div>
                <div class="mb-3">
                  <label for="inputCity" class="form-label">City</label>
                  <input type="text" class="form-control" id="city" name="city" required />
                  <div class="invalid-feedback">
                    Please enter your city.
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6 mb-3">
                    <label for="inputState" class="form-label">State</label>
                    <input type="text" class="form-control" id="state" name="state" required />
                    <div class="invalid-feedback">
                      Please enter your state.
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <label for="inputZip" class="form-label">Zip</label>
                    <input type="text" class="form-control" id="zip_code" name="zip_code" required />
                    <div class="invalid-feedback">
                      Please enter your zip code.
                    </div>
                  </div>
                </div>
                <div class="mb-3">
                  <label for="inputPhone" class="form-label">Phone Number</label>
                  <input type="tel" class="form-control" id="phone" name="phone" required />
                  <div class="invalid-feedback">
                    Please enter your phone number.
                  </div>
                </div>
                <br />
                <div class="mb-3 d-flex justify-content-center align-items-center">
                  <button id="btn" type="submit" class="btn btn-success btn-block">Place Order</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

<script>
  // Form validation
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      var forms = document.getElementsByClassName('needs-validation');
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();

  if (localStorage.getItem('cart') == null) {
    var cart = {};
  } else {
    cart = JSON.parse(localStorage.getItem('cart'));
  }

  var sum = 0;
  var totalPrice = 0;

  if ($.isEmptyObject(cart)) {
    //if object is empty
    mystr = `<p>Your cart is empty, please add some items to your cart before checking out!</p>`
    $('#cartTableBody').append(mystr);
  } else {
    for (item in cart) {
      let name = cart[item][1];
      let qty = cart[item][0];
      let itemPrice = cart[item][2];
      sum = sum + qty;
      totalPrice = totalPrice + qty * itemPrice;

      let row = `<tr>
                  <td>${name}</td>
                  <td>${qty}</td>
                  <td>${itemPrice}</td>
                  <td>${qty * itemPrice}</td>
                </tr>`;
      $('#cartTableBody').append(row);
    }
  }

  document.getElementById('totalprice').innerHTML = totalPrice;
  $('#itemsJson').val(JSON.stringify(cart));

  {% if thank %}
  alert('Thanks for ordering with us. Your order is is {{id}}. Use it to track your order using our order tracker');
  localStorage.clear();
  document.location = "/";
  {% endif %}

  document.getElementById("amt").value = totalPrice;

</script>

<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>


{% endblock body %}

ecommerce/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Home
{% endblock title %} 

{% block content %}
<section id="hero" style="width: 100%; height: 90vh; background-image: url('{% static 'images/bgg1.png' %}'); background-position: top center; background-size: cover; position: relative;">
  <div class="hero-container">  
    <h1> Welcome to Market Mingle</h1>
    <div class="section-title">
      <h3>Check our Products</h3>
    </div>
    
  </div>
</section>
{% endblock content %}

{% block body %} 
{% load static %}

<!-- ======= Portfolio Section ======= -->
<section id="portfolio" class="portfolio">
  <div class="container">
    {% for message in messages %}

    <div
      class="alert alert-{{message.tags}} alert-dismissible fade show"
      role="alert"
    >
      <strong>{{message}}</strong>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endfor %}

    

    {% for product, range, nSlides in allProds %}


    <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #ddd; padding-bottom: 15px; margin-top: 30px;">

      <!-- Category -->
      <h3 style="margin: 0; padding: 0; font: bold 24px/1.2 'Arial', sans-serif; color: #333; text-transform: capitalize;">
          {{product.0.category}}
      </h3>
  
      <!-- Subcategory -->
      <h3 style="margin: 0; padding: 0; font: 400 18px/1.2 'Arial', sans-serif; color: #666; text-transform: uppercase; letter-spacing: 1px;">
          {{product.0.subcategory}}
      </h3>
  
  </div>
  
  
  
  
      

    {% comment %} <h3 class="my-3 text-center text-success bg-light">
      {{product.0.category}}
    </h3> {% endcomment %}

    <div class="container">
      <div class="row">

        {% for i in product %}
        <div class="col-md-3 mt-3">
          <div class="card" style="width: 100%; height: 100%;">
            <a href="{% url 'product_detail' i.id %}" style="display: flex; justify-content: center; align-items: center;">
              <img src="/media/{{i.image}}" class="card-img-top" alt="not found" style="object-fit: cover; height: 300px; width: 80%;" />
            </a>
            
            
            <div class="card-body">
              <h5 class="card-title mt-2" id="namepr{{i.id}}">{{i.product_name}}</h5>
              <p class="card-text">{{i.desc|slice:"0:53"}}...</p>
              <h6 class="card-title mb-3">
                Price: <span id="pricepr{{i.id}}">{{i.price}}</span>
              </h6>
              <span id="divpr{{i.id}}" class="divpr">
                <button id="pr{{i.id}}" class="btn btn-success cart btn-sm mt-0">
                  Add To Cart <i class="fa-solid fa-cart-shopping"></i>
                </button>
              </span>

              <a href="{% url 'product_detail' i.id %}">
                <button class="btn btn-dark btn-sm cart"><i class="fa-solid fa-eye"></i></button>
              </a>
{% comment %} 
              <a href="/media/{{i.image}}">
                <button class="btn btn-dark btn-sm cart"><i class="fa-solid fa-eye"></i></button>
              </a> {% endcomment %}
            </div>
          </div>
        </div>

        {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>
</section>
<!-- End Portfolio Section -->

<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  
 
<script>
  
  //find out the cart from local storage

  if (localStorage.getItem('cart') == null) {
      var cart = {};
  } else {
      cart = JSON.parse(localStorage.getItem('cart'));
      updateCart(cart);

  }
  // add or increment code

  // $('.cart').click(function() {
  $('.divpr').on('click', 'button.cart', function() {
      var idstr = this.id.toString();
      console.log(idstr)

      if (cart[idstr] != undefined) {
          qty = cart[idstr][0] + 1;

      } else {
          qty = 1;
          name = document.getElementById('name' + idstr).innerHTML;
          price = document.getElementById('price' + idstr).innerHTML;
          cart[idstr] = [qty, name, price];
          
      }
      updateCart(cart);

      localStorage.setItem('cart', JSON.stringify(cart));
      document.getElementById('cart').innerHTML = Object.keys(cart).length;
      console.log( Object.keys(cart).length)
      // document.getElementById("popcart").click(); // Remove this line
  });
  // add popover to cart

  $('#popcart').popover();

  updatePopover(cart);
  
  function updatePopover(cart) {
      console.log('we are inside update popover');
      
      var popStr = "<h5>Cart Items</h5><div class='mx-2 my-2'><table class='table'><thead><tr><th>No.</th><th>Name</th><th>Quantity</th></tr></thead><tbody>";
      
      var i = 1;
      for (var item in cart) {
          popStr += "<tr>";
          popStr += "<td>" + i + "</td>";
          popStr += "<td>" + document.getElementById('name' + item).innerHTML.slice(0, 19) + "...</td>";
          popStr += "<td><b>" + cart[item][0] + "</b> Qty</td>";
          popStr += "</tr>";
          i++;
      }
      
      popStr += "</tbody></table></div>";
      popStr += "<a href='/checkout'><button class='btn btn-success' style='margin-left:15px'>Checkout</button></a>";
      popStr += "<button class='btn btn-dark' style='margin-left:15px' onclick='clearCart()'>Clear Cart</button>";
  
      document.getElementById('popcart').setAttribute('data-content', popStr);
  }
  
  function clearCart() {
      cart = JSON.parse(localStorage.getItem('cart'));
      for (var item in cart) {
          document.getElementById('div' + item).innerHTML = '<button id="' + item + '" class="btn btn-success cart btn-sm mt-0">Add to Cart <i class="fa-solid fa-cart-shopping"></i></button>';
      }
      localStorage.clear();
      cart = {};
      updateCart(cart);
  
      let popcart = document.getElementById("popcart");
      popcart.click();
      popcart.click(); // Double click to ensure popover is updated
  }
  

  function updateCart(cart) {
    var sum = 0;
    for (var item in cart) {
        sum += cart[item][0];
        document.getElementById('div' + item).innerHTML = "<button id='minus" + item + "' class='btn btn-success minus'>-</button> <span id='val" + item + "'>" + (cart[item][0] || " ") + "</span> <button id='plus" + item + "' class='btn btn-success plus'> + </button>";
    }
    localStorage.setItem('cart', JSON.stringify(cart));
    document.getElementById('cart').innerHTML = sum === 0 ? ' ' : sum;
    console.log(cart);
    updatePopover(cart);
}


  //if plus or minus button is clicked change the cart as well as the display value
  $('.divpr').on("click", "button.minus", function() {

      a = this.id.slice(7, );
      cart['pr' + a][0] = cart['pr' + a][0] - 1;
      cart['pr' + a][0] = Math.max(0, cart['pr' + a][0]);
      document.getElementById('valpr' + a).innerHTML = cart['pr' + a][0];
      updateCart(cart);
      

  })


  $('.divpr').on("click", "button.plus", function() {

      a = this.id.slice(6, );
      cart['pr' + a][0] = cart['pr' + a][0] + 1;

      document.getElementById('valpr' + a).innerHTML = cart['pr' + a][0];
      updateCart(cart);
      

  })
</script>

{% endblock body %}

ecommerce/templates/login.html
{% extends 'base.html' %} 
{% load static %}
{% block title %}Login{% endblock title %} 

{% block content %}
<section id="hero" style="width: 100%; height: 30vh; background-image: url('{% static 'images/dot.png' %}'); background-position: top center; background-size: cover; position: relative;">
  <div class="hero-container" style="margin-top:10%;">  
    <h1>Login</h1>
  </div>
</section>
{% endblock content %}

{% block body %}
<div class="container mt-5" style="margin-top:20px; margin-bottom:20px">
  <div class="row justify-content-center">
    <div class="col-lg-5 col-md-8 col-sm-10">
      <div class="card shadow-sm">
        <div class="card-body">
          {% for message in messages %}
          <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
          {% comment %} <h3 class="text-dark mb-4">Login</h3> {% endcomment %}
          <form action="/auth/login/" method="post">
            {% csrf_token %}
            <div class="mb-3">
              <label for="email" class="form-label">Email</label>
              <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div class="mb-3">
              <label for="pass1" class="form-label">Password</label>
              <input type="password" class="form-control" id="pass1" name="pass1" required>
            </div>
            <div class="d-grid">
              <button type="submit" class="btn btn-primary btn-lg">Login</button>
            </div>
          </form>
          <div class="mt-3 text-center">
            <span>Forget Password? <a href="/auth/request-reset-email/">Reset</a></span>
          </div>
          <div class="mt-3 text-center">
            New User? <a href="/auth/signup/">Signup</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

ecommerce/templates/login_notification.html
{% autoescape off %}

Hello {{ user.username }},

This is to inform you that you have successfully logged in to our website.

If you did not perform this action, please contact us immediately.

Thank you!

Go to Your Page

http://127.0.0.1:2000/
{% endautoescape %}

ecommerce/templates/order_confirmation_email.html
{% autoescape off %}

Order Confirmation

Thank you for your order! Here are the details:

Name: {{ order.name }}
Email: {{ order.email }}
Address: {{ order.address1 }} {{ order.address2 }}, 
City: {{ order.city }}
State: {{ order.state }}
Pincode: {{ order.zip_code }}
Phone: {{ order.phone }}

Total Amount: {{ order.amount }}

Thank you for shopping with us!

Continue Your shopping

http://127.0.0.1:2000/

{% endautoescape %}

ecommerce/templates/payment_successful_email.html
{% autoescape off %}

Payment Successful

Hello {{ order.name }},

We are pleased to inform you that your payment for order {{ order.oid }} has been successfully processed.

Order Details:
Order Id: {{ order.oid }}
Name: {{ order.name }}
Email: {{ order.email }}
Amount: {{ order.amount }}

Thank you for shopping with us!

Continue Your shopping

http://127.0.0.1:2000/
{% endautoescape %}

ecommerce/templates/paymentstatus.html
{% extends 'base.html' %}
{% block title %}Payment Status{% endblock title %}
{% load static %}
{% block content %}
<section id="hero" style="width: 100%; height: 30vh; background-image: url('{% static 'images/dot.png' %}'); background-position: top center; background-size: cover; position: relative;">
  <div class="hero-container" style="margin-top:10%;">  
    <h1>Payment Status</h1>
  </div>
</section>
{% endblock content %}

{% block body %}
<div class="container mt-4" style="margin-bottom:20px">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-lg">
                <div class="card-header bg-success text-white">
                    <h4 class="mb-0">Payment Status</h4>
                </div>
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col-md-4 text-center">
                            <i class="fas fa-check-circle fa-5x text-success mb-3"></i>
                        </div>
                        <div class="col-md-8">
                            <p style="color: #2ecc71;"><strong>Status:</strong> Payment successful!</p>
                            {% comment %} <p class="mb-3">Payment status regarding your order</p> {% endcomment %}
                            <p><strong>Order Id:</strong> {{ order.oid }}</p>
                            <p><strong>Payment ID:</strong> {{ response.razorpay_payment_id }}</p>
                            <p><strong>Amount:</strong> Rs: {{ order.amount }}</p>
                        </div>
                        <div class="col-md-12 text-center mt-4">
                            <a href="/" class="btn btn-success mx-1 btn-sm">Continue Shopping</a>
                            <a href="/profile" class="btn btn-success mx-1 btn-sm">Track Order</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

ecommerce/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}My Orders{% endblock title %}

{% block content %}
<section id="hero" style="width: 100%; height: 90vh; background-image: url('{% static 'images/delivery.png' %}'); background-position: top center; background-size: cover; position: relative;">
  <div class="hero-container">  
    <h1>My Orders</h1>
  </div>
</section>
{% endblock content %}

{% block body %}
<section id="portfolio" class="portfolio">
    <div class="container">
        <div class="table-responsive">
            <table class="table" style="border-collapse: collapse; width: 100%; outline: 2px solid black;">
                <thead>
                    <tr style="border-bottom: 2px solid #000;">
                        <th scope="col" style="padding: 8px;">Order ID</th>
                        <th scope="col" style="padding: 8px;">Name</th>
                        <th scope="col" style="padding: 8px;">Products</th>
                        <th scope="col" style="padding: 8px;">Amount Paid</th>
                        <th scope="col" style="padding: 8px;">Payment Status</th>
                        <th scope="col" style="padding: 8px;">Address</th>
                        <th scope="col" style="padding: 8px;">Phone Number</th>
                        <th scope="col" style="padding: 8px;">Delivery Status</th>
                        <th scope="col" style="padding: 8px;">Delivered</th>
                        {% comment %} <th scope="col" style="padding: 8px;">Date</th> {% endcomment %}
                    </tr>
                </thead>
                <tbody>
                    {% for order in items %}
                    <tr style="border-bottom: 1px solid #000;">
                        <td style="padding: 8px;">{{ order.oid }}</td>
                        <td style="padding: 8px;">{{ order.name }}</td>
                        <td style="padding: 8px;">{{ order.items_json }}</td>
                        <td style="padding: 8px;">{{ order.amount }}</td>
                        {% comment %} <td style="padding: 8px;">{{ order.paymentstatus }}</td> {% endcomment %}
                        <td style="padding: 8px;"><i class="fas fa-check-circle fa-1x text-success mb-3"></i></td>
                        <td style="padding: 8px;">{{ order.address1 }} {{ order.address2 }}</td>
                        <td style="padding: 8px;">{{ order.phone }}</td>
                        <td style="padding: 8px;">
                                <i class="fa-solid fa-truck"></i> Not Delivered
                        </td>
                        <td style="padding: 8px;">
                            <i class="fas fa-times-circle fa-1x text-danger mb-3"></i>
                        </td>
                        
                        {% comment %} <td style="padding: 8px;">
                            {% for update in order.orderupdate_set.all %}
                                {{ update.update_desc }} <br>
                            {% endfor %}
                        </td>
                        <td style="padding: 8px;">
                            {% if update.delivered %}
                                <i class="fa-solid fa-circle-check"></i> Delivered
                            {% else %}
                                <i class="fa-solid fa-truck"></i> Not Delivered
                            {% endif %}
                        </td> {% endcomment %}
                        {% comment %} <td style="padding: 8px;">{{ update.timestamp }}</td> {% endcomment %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock body %}

ecommerce/templates/razorpay.html
{% extends 'base.html' %}
{% block title %}Payment{% endblock title %}
{% load static %}
{% block content %}
<section id="hero" style="width: 100%; height: 30vh; background-image: url('{% static 'images/dot.png' %}'); background-position: top center; background-size: cover; position: relative;">
  <div class="hero-container" style="margin-top:10%;">  
    <h1>Payment</h1>
  </div>
</section>
{% endblock content %}

{% block body %}
<div class="payment-form-container" style="display: flex; justify-content: center; align-items: center; height: 20vh;">
  <form action="/handlerequest/" method="POST" class="payment-form" style="text-align: center;">
    {% csrf_token %}
    <script
            src="https://checkout.razorpay.com/v1/checkout.js"
            data-key="rzp_test_VcfYYWbvSUfKU4"
            data-amount="{{ amount }}"
            data-currency="INR"
            data-order_id="{{ order_id }}"
            data-name="Market Mingle"
            data-description="Purchase Description"
            data-image="{% static 'images/LOGO1.png' %}"
            data-prefill.name="{{ name }}"
            data-prefill.email="{{ email }}"
            data-theme.color="#22bf76"
    ></script>
    <style>
      .razorpay-payment-button {
        display: none !important;
      }
    </style>
    <input type="hidden" custom="Hidden Element" name="hidden">
    <button type="submit" class="btn btn-success btn-lg mt-3">Proceed to Pay</button>
  </form>
</div>
{% endblock body %}

ecommerce/templates/reset-user-password.html
{% autoescape off %}
HI there,
Please Click the below link to reset your Password kindly do not share with this anyone 

http://{{domain}}{% url 'set-new-password' uidb64=uid token=token %}
    
{% endautoescape %}